### PR TITLE
Fix: env0_aws_credentials - apply after import will delete+create

### LINKED ISSUE #99: env0_aws_credentials - apply after import will delete+create
1. Create a Cloud Credential
2. Create the TF config for it
3. Do a `terraform import` on it
4. Apply- you will be prompted that the credential will be replaced

This is probably because we don't get the full state of the credential on the import.

### PR DESCRIPTION
**Pull request by TomerHeber**
I'm keeping open, to adding support for other credential types.

### Solution
Added import.
Removed a schema requirements and instead enforce during read.
Added acceptance tests.
Added a "resource" tag.
Added import examples.
Fixed some other issues I noticed.

### CODE REVIEW

File: client/cloud_credentials.go [hunk 1]
```diff
@@ -37,7 +33,7 @@ type AwsCredentialsCreatePayload struct {
 }
 
 type AwsCredentialsValuePayload struct {
-	RoleArn         string `json:"roleArn"`
+	RoleArn         string `json:"roleArn" resource:"arn"`
```
Comment (TomerHeber) [inline client/cloud_credentials.go:36]: new tag type for serialization. See usage below.
(Basically in terraform the resource is "arn" and not "role_arn" - so needed to resolve this).

File: client/cloud_credentials.go [hunk 2]
```diff
@@ -89,7 +85,7 @@ func (client *ApiClient) CloudCredentials(id string) (Credentials, error) {
 		}
 	}
 
-	return Credentials{}, fmt.Errorf("CloudCredentials: [%s] not found ", id)
+	return Credentials{}, &NotFoundError{}
```
Comment (TomerHeber) [inline client/cloud_credentials.go:88]: Used to handle drift later.

File: env0/credentials.go [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+import (
+	"fmt"
+	"log"
+	"strings"
+
+	"github.com/env0/terraform-provider-env0/client"
+	"github.com/google/uuid"
+)
+
+func getCredentialsByName(name string, prefix string, meta interface{}) (client.Credentials, error) {
```
Comment (TomerHeber) [inline env0/credentials.go:12]: Common helper functions for credentials (can be used by GCP and Azure in the future). (In case import is added to them as well).

File: env0/data_notification.go [hunk 4]
```diff
@@ -61,7 +61,7 @@ func dataNotificationRead(ctx context.Context, d *schema.ResourceData, meta inte
 	}
 
 	if err := writeResourceData(notification, d); err != nil {
-		diag.Errorf("schema resource data serialization failed: %v", err)
+		return diag.Errorf("schema resource data serialization failed: %v", err)
```
Comment (TomerHeber) [inline env0/data_notification.go:64]: bug.

Comment (TomerHeber) [reply env0/data_notification.go:64]: there are a few places with the same bug...

File: env0/resource_aws_credentials.go [hunk 5]
```diff
@@ -27,7 +30,6 @@ func resourceAwsCredentials() *schema.Resource {
 				Optional:      true,
 				ForceNew:      true,
 				ConflictsWith: []string{"access_key_id"},
-				ExactlyOneOf:  []string{"access_key_id"},
```
Comment (TomerHeber) [inline env0/resource_aws_credentials.go:30]: The "ExactlyOneOf" cannot be inforced in the schema level. (Will fail on import).

File: env0/resource_aws_credentials.go [hunk 6]
```diff
@@ -62,29 +63,32 @@ func resourceAwsCredentials() *schema.Resource {
 }
 
 func resourceAwsCredentialsCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
+	_, accessKeyExist := d.GetOk("access_key_id")
```
Comment (TomerHeber) [inline env0/resource_aws_credentials.go:66]: Enforcing the exactlyOnce in the code level only for creation (not for read/import).

File: env0/resource_aws_credentials.go [hunk 7]
```diff
@@ -62,29 +63,32 @@ func resourceAwsCredentials() *schema.Resource {
...
 
 	value := client.AwsCredentialsValuePayload{}
-	requestType := client.AwsAssumedRoleCredentialsType
-	if arn, ok := d.GetOk("arn"); ok {
-		value.RoleArn = arn.(string)
-		requestType = client.AwsAssumedRoleCredentialsType
-	}
-	if externalId, ok := d.GetOk("external_id"); ok {
-		value.ExternalId = externalId.(string)
+	if err := readResourceData(&value, d); err != nil {
```
Comment (TomerHeber) [inline env0/resource_aws_credentials.go:77]: some small refactoring (less lines of code).

File: env0/utils.go [hunk 8]
```diff
@@ -42,7 +42,13 @@ func readResourceData(i interface{}, d *schema.ResourceData) error {
 	for i := 0; i < val.NumField(); i++ {
 		fieldName := val.Type().Field(i).Name
 		// Assumes golang is CamalCase and Terraform is snake_case.
+		// This behavior can be overrided be used in the 'resource' tag.
 		fieldNameSC := toSnakeCase(fieldName)
+		if resFieldName, ok := val.Type().Field(i).Tag.Lookup("resource"); ok {
```
Comment (TomerHeber) [inline env0/utils.go:47]: This is for the new tag I created (resource). Ping me if this is still unclear.

File: env0/resource_aws_credentials_test.go [hunk 9]
```diff
@@ -108,7 +116,7 @@ func TestUnitAwsCredentialsResource(t *testing.T) {
 		Steps: []resource.TestStep{
 			{
 				Config:      resourceConfigCreate(resourceType, resourceName, mutuallyExclusiveErrorResource),
-				ExpectError: regexp.MustCompile("only one of `access_key_id,arn` can be specified"),
+				ExpectError: regexp.MustCompile(`"external_id": conflicts with access_key_id`),
```
Comment (TomerHeber) [inline env0/resource_aws_credentials_test.go:119]: There are multiple errors., the following just come before.

File: env0/resource_aws_credentials.go [hunk 10]
```diff
@@ -98,11 +102,14 @@ func resourceAwsCredentialsCreate(ctx context.Context, d *schema.ResourceData, m
...
 
-	id := d.Id()
-	_, err := apiClient.CloudCredentials(id)
+	credentials, err := apiClient.CloudCredentials(d.Id())
 	if err != nil {
 		return ResourceGetFailure("aws credentials", d, err)
 	}
+
+	d.Set("name", credentials.Name)
+	d.SetId(credentials.Id)
```
Comment (yaronya) [inline env0/resource_aws_credentials.go:111]: Can we use the seralization logic here instead?

File: env0/resource_aws_credentials.go [hunk 11]
```diff
@@ -116,3 +123,18 @@ func resourceAwsCredentialsDelete(ctx context.Context, d *schema.ResourceData, m
...
+	credentials, err := getCredentials(d.Id(), "AWS_", meta)
+	if err != nil {
+		if _, ok := err.(*client.NotFoundError); ok {
+			return nil, fmt.Errorf("aws credentials resource with id %v not found", d.Id())
+		}
+		return nil, err
+	}
+
+	d.Set("name", credentials.Name)
+	d.SetId(credentials.Id)
```
Comment (yaronya) [inline env0/resource_aws_credentials.go:137]: Same question here

File: env0/utils.go (hunk 8 above)
Comment (yaronya) [reply env0/utils.go:47]: Very cool 👏 
Just wondering together with you whether `resourcee` is a decent tag name or we can come up with a better name. Maybe something that indicates that this is related to the TF schema would do better.

Also - WDYT about adding some note regarding it in `DEVELOPMENT.md`?

**Review by yaronya — COMMENTED** [review]
Nice work!
Left some few minor comments

File: env0/utils.go (hunk 8 above)
Comment (TomerHeber) [reply env0/utils.go:47]: yes and yes.
How about tfschema or tfresource ? (I'm bad with names).

Comment (yaronya) [reply env0/utils.go:47]: Both are better. If you want me to choose then I'd go with `tschema` 😅

File: env0/resource_aws_credentials.go (hunk 10 above)
Comment (TomerHeber) [reply env0/resource_aws_credentials.go:111]: yeah sure. In general, I use it when there a multiple fields.
Either way is fine by me. I'll fix it.

File: env0/resource_aws_credentials.go (hunk 11 above)
Comment (TomerHeber) [reply env0/resource_aws_credentials.go:137]: same answer.

File: env0/utils.go (hunk 8 above)
Comment (TomerHeber) [reply env0/utils.go:47]: we have a winner (:

File: env0/resource_aws_credentials.go [hunk 12]
```diff
@@ -14,6 +15,8 @@ func resourceAwsCredentials() *schema.Resource {
 		ReadContext:   resourceAwsCredentialsRead,
 		DeleteContext: resourceAwsCredentialsDelete,
 
+		Importer: &schema.ResourceImporter{StateContext: resourceAwsCredentialsImport},
```
Comment (yaronya) [inline env0/resource_aws_credentials.go:18]: @TomerHeber if we're already at it, can we perhaps also support import for all other credentials type? I'd do it in a separate PR tho

File: env0/resource_aws_credentials.go (hunk 10 above)
Comment (yaronya) [reply env0/resource_aws_credentials.go:111]: I think always using it makes a lot of sense since we wouldn't need to change anything when we'll add a new field 💪

File: env0/resource_aws_credentials.go (hunk 12 above)
Comment (TomerHeber) [reply env0/resource_aws_credentials.go:18]: keeping the issue open.

File: env0/resource_aws_credentials.go (hunk 10 above)
Comment (TomerHeber) [reply env0/resource_aws_credentials.go]: done!
