### PR TITLE
Fix: have a good default for approval flow on workflows

### LINKED ISSUE #1023: Have a good default for approval flow on workflows
**Describe the bug**
Today when deploying a basic workflow environment  with the provider it's common to get the error 

```
╷
│ Error: could not create environment: 400 Bad Request: approval flow can't be enabled on workflow environments
│
│   with env0_environment.provider_workflow,
│   on main.tf line 22, in resource "env0_environment" "provider_workflow":
│   22: resource "env0_environment" "provider_workflow" {
│
```
This can be fixed by setting `approve_plan_automatically = true`

**To Reproduce**
Deploy a basic workflow environment with the environment without specifying approve_plan_automatically

**Expected behavior**
The environment should be created even without specifying approve_plan_automatically

**Provider Version**
E.g.: 1.25.1

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #1023 

### Solution

1. During creating isWorkflow is decided based on the template type instead of the sub_environment_configuration.
2. When updating schema - ignore "approve_plan_automatically" if not set in schema - this is a cleaner solution.
3. Applied minor updates to acceptance tests.

### CODE REVIEW

File: env0/resource_environment.go
Comment (eranelbaz) [inline env0/resource_environment.go:1]: Those are a lot of changes for the approval flow, can you explain what did you do here?

Comment (TomerHeber) [reply env0/resource_environment.go:1]: yes. the change is a litte complex.

File: env0/resource_environment.go [hunk 1]
```diff
@@ -550,20 +550,66 @@ func createVariable(configurationVariable *client.ConfigurationVariable) any {
 }
 
 // Validate that the template is assigned to the "project_id".
-func validateTemplateProjectAssignment(d *schema.ResourceData, apiClient client.ApiClientInterface) error {
+func validateTemplateProjectAssignment(d *schema.ResourceData, template *client.Template) error {
```
Comment (TomerHeber) [inline env0/resource_environment.go:553]: need the template in one of the upper functions, so here instead of getting it we pass it here.
we get it from the upper functions.

File: env0/resource_environment.go [hunk 2]
```diff
@@ -550,20 +550,66 @@ func createVariable(configurationVariable *client.ConfigurationVariable) any {
...
+		return errors.New("could not create environment: template is not assigned to project")
+	}
+
+	return nil
+}
+
+func createEnvironmentWithTemplate(d *schema.ResourceData, apiClient client.ApiClientInterface) (client.Environment, client.EnvironmentCreate, diag.Diagnostics) {
 	templateId := d.Get("template_id").(string)
 
 	template, err := apiClient.Template(templateId)
```
Comment (TomerHeber) [inline env0/resource_environment.go:557]: this is why this part was removed.

File: env0/resource_environment.go [hunk 3]
```diff
@@ -550,20 +550,66 @@ func createVariable(configurationVariable *client.ConfigurationVariable) any {
...
 	projectId := d.Get("project_id").(string)
+
+	if projectId != template.ProjectId && !stringInSlice(projectId, template.ProjectIds) {
+		return errors.New("could not create environment: template is not assigned to project")
+	}
+
+	return nil
+}
+
+func createEnvironmentWithTemplate(d *schema.ResourceData, apiClient client.ApiClientInterface) (client.Environment, client.EnvironmentCreate, diag.Diagnostics) {
```
Comment (TomerHeber) [inline env0/resource_environment.go:563]: we have two usecases.
template and envrionment seperate resources.
template + environment one resource.
previousuly it was an if-else in the code. now it's two helper functions with a if-else.

File: env0/resource_environment.go [hunk 4]
```diff
@@ -550,20 +550,66 @@ func createVariable(configurationVariable *client.ConfigurationVariable) any {
...
 	}
 
-	if projectId != template.ProjectId && !stringInSlice(projectId, template.ProjectIds) {
-		return errors.New("could not create environment: template is not assigned to project")
+	if err := validateTemplateProjectAssignment(d, &template); err != nil {
+		return client.Environment{}, client.EnvironmentCreate{}, diag.Errorf("%v", err)
 	}
 
-	return nil
+	environmentPayload, diagError := getCreatePayload(d, apiClient, template.Type)
```
Comment (TomerHeber) [inline env0/resource_environment.go:575]: we pass the template.Type - with this we set a better default.

File: env0/resource_environment.go [hunk 5]
```diff
@@ -550,20 +550,66 @@ func createVariable(configurationVariable *client.ConfigurationVariable) any {
...
+
+	environment, err := apiClient.EnvironmentCreate(environmentPayload)
+	if err != nil {
+		return client.Environment{}, client.EnvironmentCreate{}, diag.Errorf("could not create environment: %v", err)
+	}
+
+	return environment, environmentPayload, nil
+}
+
+func createEnvironmentWithoutTemplate(d *schema.ResourceData, apiClient client.ApiClientInterface) (client.Environment, client.EnvironmentCreate, diag.Diagnostics) {
```
Comment (TomerHeber) [inline env0/resource_environment.go:588]: helper function 2 - environment + template together.

File: env0/resource_environment.go [hunk 6]
```diff
@@ -550,20 +550,66 @@ func createVariable(configurationVariable *client.ConfigurationVariable) any {
...
+
+	payload := client.EnvironmentCreateWithoutTemplate{
+		EnvironmentCreate: environmentPayload,
+		TemplateCreate:    templatePayload,
+	}
+
+	// Note: the blueprint id field of the environment is returned only during creation of a template without environment.
+	// Afterward, it will be omitted from future response.
+	// setEnvironmentSchema() sets the blueprint id in the resource (under "without_template_settings.0.id").
+	environment, err := apiClient.EnvironmentCreateWithoutTemplate(payload)
```
Comment (TomerHeber) [inline env0/resource_environment.go:607]: the payload contains the template details which means it contains the template Type which we need for better defaults.

File: env0/resource_environment.go [hunk 7]
```diff
@@ -573,41 +619,20 @@ func resourceEnvironmentCreate(ctx context.Context, d *schema.ResourceData, meta
...
+	var environmentPayload client.EnvironmentCreate
 
-	if !isTemplateless(d) {
-		if err := validateTemplateProjectAssignment(d, apiClient); err != nil {
-			return diag.Errorf("%v\n", err)
-		}
+	var diagError diag.Diagnostics
 
-		environment, err = apiClient.EnvironmentCreate(environmentPayload)
+	if !isTemplateless(d) {
```
Comment (TomerHeber) [inline env0/resource_environment.go:628]: this is the if-else where we call the two helper functions.

File: env0/resource_environment.go [hunk 8]
```diff
@@ -1016,7 +1041,7 @@ func getCreatePayload(d *schema.ResourceData, apiClient client.ApiClientInterfac
 		payload.AutoDeployOnPathChangesOnly = boolPtr(val.(bool))
 	}
 
-	_, isWorkflow := d.GetOk("sub_environment_configuration")
+	isWorkflow := templateType == client.WORKFLOW
```
Comment (TomerHeber) [inline env0/resource_environment.go:1044]: and finally we decide if it's a workflow based on the templateType.
if isWorkflow is True, defaults will be set as needed. This code already exist.
The change is - we decide if it's a workflow based on the template type instead of checking if sub_environment_configuration exist.

File: env0/resource_environment.go [hunk 9]
```diff
@@ -441,8 +441,8 @@ func setEnvironmentSchema(ctx context.Context, d *schema.ResourceData, environme
 		d.Set("output", string(environment.LatestDeploymentLog.Output))
 	}
 
-	// Don't update this value for workflow environments - this value should always be 'false'.
-	if _, isWorkflow := d.GetOk("sub_environment_configuration"); !isWorkflow && environment.RequiresApproval != nil {
+	//nolint:staticcheck // https://github.com/hashicorp/terraform-plugin-sdk/issues/817
+	if _, exists := d.GetOkExists("approve_plan_automatically"); exists && environment.RequiresApproval != nil {
```
Comment (TomerHeber) [inline env0/resource_environment.go:445]: only make changes to approve_plan_automatically if someone has set a value for it.
it's tri-boolean value.
undefined, true, and false.

File: env0/resource_environment.go (hunk 3 above)
Comment (TomerHeber) [inline env0/resource_environment.go:563]: environemnt and template - seperate resources use-case.

File: env0/resource_environment.go (hunk 2 above)
Comment (eranelbaz) [inline env0/resource_environment.go:566]: taste `templateErr`

File: env0/resource_environment.go (hunk 6 above)
Comment (eranelbaz) [inline env0/resource_environment.go:607]: taste `createEnvironmentErr`

File: env0/resource_environment.go [hunk 10]
```diff
@@ -573,41 +619,20 @@ func resourceEnvironmentCreate(ctx context.Context, d *schema.ResourceData, meta
...
 	var environment client.Environment
 
-	var err error
+	var environmentPayload client.EnvironmentCreate
 
-	if !isTemplateless(d) {
-		if err := validateTemplateProjectAssignment(d, apiClient); err != nil {
-			return diag.Errorf("%v\n", err)
-		}
+	var diagError diag.Diagnostics
```
Comment (eranelbaz) [inline env0/resource_environment.go:626]: instead of `diagError` create env error?

**Review by eranelbaz — APPROVED** [review]
After talking seems ok to me
note name suggestions

File: env0/resource_environment.go (hunk 2 above)
Comment (TomerHeber) [reply env0/resource_environment.go:566]: The common/standard coding convention in golang is "err".
I will keep as is.

File: env0/resource_environment.go (hunk 6 above)
Comment (TomerHeber) [reply env0/resource_environment.go:607]: The common/standard coding convention in golang is "err".
I will keep as is.

**Comment by TomerHeber** [comment]
@eranelbaz - going to merge. If you still want to make naming changes let me know and I create an additional PR. But note that I've used common naming conventions.
