### PR TITLE
Fix: changing variable scope

### LINKED ISSUE #332: Bug report : Changing variable scope
> I had a variable set to a template scope, then changed it to global, and it didn't show up in the global variables section. I ran terraform taint on it and it showed up and worked as expected, but the modify by itself didn't do that for some reason.

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #332 

### Solution
Added ForceNew to project_id, template_id, and environment_id.

### CODE REVIEW

**Review by sabasabo — APPROVED** [review]
LGTM

File: env0/resource_configuration_variable.go [hunk 1]
```diff
@@ -51,18 +51,21 @@ func resourceConfigurationVariable() *schema.Resource {
...
 				Optional:      true,
 				ConflictsWith: []string{"project_id", "environment_id"},
+				ForceNew:      true,
 			},
 			"environment_id": {
 				Type:          schema.TypeString,
 				Description:   "create the variable under this environment, not globally",
 				Optional:      true,
 				ConflictsWith: []string{"template_id", "project_id", "is_required", "is_read_only"},
+				ForceNew:      true,
```
Comment (yaronya) [inline env0/resource_configuration_variable.go:68]: Please also apply this to the `type` attribute of the schema. API doesn't support changing an existing variable's type

Comment (TomerHeber) [reply env0/resource_configuration_variable.go:68]: added.
