### PR TITLE
Fix: env0_gcp_credentials - apply after import will delete+create

### LINKED ISSUE #99: env0_aws_credentials - apply after import will delete+create
1. Create a Cloud Credential
2. Create the TF config for it
3. Do a `terraform import` on it
4. Apply- you will be prompted that the credential will be replaced

This is probably because we don't get the full state of the credential on the import.

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #99 
The last part of the effort to add import to all credential types (Azure and AWS is complete).

### Solution
1. Added import.
2. Fixed some bugs.
3. Added acceptance tests.
4. Added examples.

### CODE REVIEW

File: env0/resource_gcp_credentials_test.go [hunk 1]
```diff
@@ -23,7 +26,7 @@ func TestUnitGcpCredentialsResource(t *testing.T) {
 	}
 
 	updateGcpCredentialResource := map[string]interface{}{
-		"name":                "testUpdate",
```
Comment (TomerHeber) [inline env0/resource_gcp_credentials_test.go:26]: bug in test.

File: env0/resource_gcp_credentials.go [hunk 2]
```diff
@@ -67,10 +72,15 @@ func resourceGcpCredentialsRead(ctx context.Context, d *schema.ResourceData, met
...
 	id := d.Id()
-	_, err := apiClient.CloudCredentials(id)
+	credentials, err := apiClient.CloudCredentials(id)
 	if err != nil {
 		return ResourceGetFailure("gcp credentials", d, err)
 	}
+
+	if err := writeResourceData(&credentials, d); err != nil {
+		return diag.Errorf("schema resource data serialization failed: %v", err)
+	}
```
Comment (razbensimon) [inline env0/resource_gcp_credentials.go:82]: Just asking, what changed that we now need it than before?
Is `import` flow will not work without it?

**Review by razbensimon — APPROVED** [review]
👏🏼

File: env0/resource_gcp_credentials.go (hunk 2 above)
Comment (TomerHeber) [reply env0/resource_gcp_credentials.go:82]: @razbensimon ,

The writeResourceData (and readReasourceData) is a utility function that reads all the fields in the interface and updates the schema via `set` calls.
This is future proof: in case you add more fields to the schema/api - no additional coding is needed (other than updating the schema).

There is a potential bug here that drifting is not detected (E.g., if someone changes the name in the UX). Once I added this code, it caught a bug in the tests as well (so I fixed the tests as well).
Import flow will work without it, and I just fixed bugs I encountered on the way.
