### PR TITLE
Fix: lexicographical sorting of configuration items

### LINKED ISSUE #459: lexicographical sorting of configuration items
I am trying to define my environment's configuration options using a map and a dynamic block.  I am doing this to make the terraform file much more readable and easier to maintain.  

Here is an example
```
locals {
  db-config = {
    allocated_storage = "40"
    db_instance_class = "db.t3.small"
    db_user           = "dbuser"
    service           = "myservice"
  }
}
resource "env0_environment" "automatron-db" {
  name       = "testdb"
  project_id = data.env0_project.this.id

  template_id                = data.env0_template.rds.id
  approve_plan_automatically = false
  deploy_on_push             = true
  run_plan_on_pull_requests  = true
  vcs_commands_alias         = "test-db"

  dynamic "configuration" {
    for_each = local.db-config
    content {
      name        = configuration.key
      value       = configuration.value
      type        = "terraform"
      schema_type = "string"
    }
  }
}

```

This code will apply and works great.  I can then create separate dynamic configuration blocks if I need to have a different type.  I find it much easier to read and adjust the settings compared to having each configuration setting block defined separately.

The problem is that future plans regularly want to update all of the configuration blocks that the dynamic block had created.  What I have determined is that the provider gets the options in a different order then what the map is in.  Terraform maps are automatically sorted in lexicographical order.  Its worth noting that if I look at the configuration options using terraform state show they are also listed in lexicographical order.  But when I run terraform plan, they seem to be returned in a different order.

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
Fixes #459 

### Solution
Maintains ordering of state as much as possible (vs the order returned by the API).
Added and updated acceptance tests accordingly.

### CODE REVIEW

File: env0/resource_environment.go [hunk 1]
```diff
@@ -178,6 +178,7 @@ func resourceEnvironment() *schema.Resource {
 							Type:        schema.TypeString,
 							Description: "the type the variable must be of",
 							Optional:    true,
+							Default:     "string",
```
Comment (TomerHeber) [inline env0/resource_environment.go:181]: I checked... this value is always returned from the backend.

File: env0/resource_environment.go [hunk 2]
```diff
@@ -277,43 +278,97 @@ func setEnvironmentSchema(d *schema.ResourceData, environment client.Environment
 	return nil
 }
 
+func createVariable(configurationVariable *client.ConfigurationVariable) interface{} {
```
Comment (TomerHeber) [inline env0/resource_environment.go:281]: This is not new code. I just moved it to a function.

File: env0/resource_environment.go [hunk 3]
```diff
@@ -277,43 +278,97 @@ func setEnvironmentSchema(d *schema.ResourceData, environment client.Environment
...
+		variable["schema_enum"] = configurationVariable.Schema.Enum
+		variable["schema_format"] = configurationVariable.Schema.Format
+	}
+
+	return variable
+}
+
 func setEnvironmentConfigurationSchema(d *schema.ResourceData, configurationVariables []client.ConfigurationVariable) {
-	var variables []interface{}
+	ivariables, ok := d.GetOk("configuration")
```
Comment (TomerHeber) [inline env0/resource_environment.go:323]: date_environment does not have the configuration field. Without GetOk, this will crash.

File: env0/resource_environment.go [hunk 4]
```diff
@@ -277,43 +278,97 @@ func setEnvironmentSchema(d *schema.ResourceData, environment client.Environment
...
-			variable["is_read_only"] = configurationVariable.IsReadOnly
+	if ivariables == nil {
+		ivariables = make([]interface{}, 0)
+	}
+
+	variables := ivariables.([]interface{})
+
+	newVariables := make([]interface{}, 0)
+
+	// The goal is to maintain existing state order as much as possible. (The backend response order may vary from state).
```
Comment (TomerHeber) [inline env0/resource_environment.go:336]: comments explain it. Also you can see it in the unit test.
The order of the state and the order returned from the API may vary.

To avoid drifts we try to keep the order as described in the state.

File: env0/resource_environment_test.go [hunk 5]
```diff
@@ -486,7 +486,88 @@ func TestUnitEnvironmentResource(t *testing.T) {
...
-				mock.EXPECT().ConfigurationVariablesByScope(client.ScopeEnvironment, environment.Id).Times(1).Return(client.ConfigurationChanges{}, nil) // read after create -> on update -> read after update
+				mock.EXPECT().ConfigurationVariablesByScope(client.ScopeEnvironment, environment.Id).Times(1).Return(client.ConfigurationChanges{configurationVariables}, nil) // read after create -> on update -> read after update
+				mock.EXPECT().Environment(environment.Id).Times(1).Return(environment, nil)
+
+				mock.EXPECT().EnvironmentDestroy(environment.Id).Times(1)
+			})
+		})
+
+		// Tests use-cases where the response returned by the backend varies from the order of the state.
+		t.Run("Create unordered configuration variables", func(t *testing.T) {
```
Comment (TomerHeber) [inline env0/resource_environment_test.go:497]: The state is order is conf1 conf2.
The API response is conf2 conf1.

This test failed without my fix. After my fix this test passes.

File: env0/resource_environment_test.go [hunk 6]
```diff
@@ -415,7 +415,7 @@ func TestUnitEnvironmentResource(t *testing.T) {
 				mock.EXPECT().Template(environment.LatestDeploymentLog.BlueprintId).Times(1).Return(template, nil)
 				mock.EXPECT().EnvironmentCreate(gomock.Any()).Times(1).Return(environment, nil)
 
-				mock.EXPECT().ConfigurationVariablesByScope(client.ScopeEnvironment, environment.Id).Times(1).Return(client.ConfigurationChanges{}, nil) // read after create -> on update -> read after update
+				mock.EXPECT().ConfigurationVariablesByScope(client.ScopeEnvironment, environment.Id).Times(1).Return(client.ConfigurationChanges{configurationVariables}, nil) // read after create -> on update -> read after update
```
Comment (TomerHeber) [inline env0/resource_environment_test.go:418]: The test was incorrect. In truth, this is the real use-case (configurations are returned).

**Review by eladmosh — APPROVED** [review]
