### PR TITLE
Fix: CD and PR plan settings on environment are not applied correctly

### LINKED ISSUE #471: CD and PR plan settings on environment are not applied correctly
Step to reproduce:
1. Create a new project.
2. Go to the project settings  -> policies.
3. Make sure that in the Continuous Deployment section both `Run Terraform plan on Pull Requests` and `Redeploy on every push` are enabled.
4. Create a new environment using the terraform provider and set the `deploy_on_push` to false and `run_plan_on_pull_requests ` to false.
5. Once the environment is created, run another `terraform plan` without changing anything. 
6. The plan will say it's going to change the `deploy_on_push` and the `run_plan_on_pull_requests ` from `true` to `false
7. You can also check the UI and see that under the environment in the settings tab that both PR plan and CD are enabled.

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #471 

### Solution

Using GetOkExist.
Updarted unit tests.

The bug was that HasChange behaves the same for field not set and false.
The only way around it is to use GetOkExist. The supports: true, false, and unset. (All 3 modes are required).

### CODE REVIEW

File: env0/resource_environment_test.go [hunk 1]
```diff
@@ -601,11 +605,10 @@ func TestUnitEnvironmentResource(t *testing.T) {
 					BlueprintId: "template-id",
 				},
 
-				AutoDeployOnPathChangesOnly: &truthyFruity,
```
Comment (TomerHeber) [inline env0/resource_environment_test.go:604]: Switched order... start with false, and update to true.

Comment (TomerHeber) [reply env0/resource_environment_test.go:604]: initially without the fixes, false would be ignored as not set.
