### PR TITLE
Fix: "all_teams" data resource causes 429 status code requests

### LINKED ISSUE #987: `"all_teams"` data resource causes `429` status code requests
**Describe the bug**
when using the data resource `"all_teams"` for many internal modules in a configuration, the api rate limit is reached.

**To Reproduce**
```
module.tf:

terraform {
  required_providers {
    env0 = {
      source  = "env0/env0"
      version = "1.22.1"
    }
  }
}

data "env0_teams" "all_teams" {}

---

main.tf:
<init provider and with API keys>

module "project_names" {
  count  = 1001
  source = "./module"
}

```

run this config from 2 different directories from the same computer at the same time

**Expected behavior**
not getting API rate limit for a constant data request

**Provider Version**
1.22.1

**Screenshots**
image

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #987 

### Solution

Added memorization to the get teams call.
This caches results between terraform executions.

The downside is that the results will be stale during the execution.

### CODE REVIEW

File: client/configuration_variable_test.go [hunk 1]
```diff
@@ -309,7 +308,7 @@ func TestConfigurationVariableMarshelling(t *testing.T) {
 
 	b, err := json.Marshal(&variable)
 	if assert.NoError(t, err) {
-		assert.False(t, strings.Contains(string(b), str))
+		assert.NotContains(t, string(b), str)
```
Comment (TomerHeber) [inline client/configuration_variable_test.go:311]: linter complaints...

File: client/memoize.go [hunk 2]
```diff
@@ -0,0 +1,22 @@
+package client
```
Comment (TomerHeber) [inline client/memoize.go:1]: generic memoization function.

File: env0/data_teams.go [hunk 3]
```diff
@@ -11,6 +11,7 @@ import (
 func dataTeams() *schema.Resource {
 	return &schema.Resource{
 		ReadContext: dataTeamsRead,
+		Description: "Note: this data source is cached, once fetched it will not be updated until the next plan/apply",
```
Comment (TomerHeber) [inline env0/data_teams.go:14]: added this note so users understand limitations.

**Review by sagilaufer1992 — COMMENTED** [review]
some tests are in order I believe. the implementation looks great, but let's make sure stuff are tested properly

**Comment by TomerHeber** [comment]
> some tests are in order I believe. the implementation looks great, but let's make sure stuff are tested properly

@sagilaufer1992 

It's already covered by some tests (acceptance and harness).
Any specific use cases you had in mind?

**Comment by sagilaufer1992** [comment]
> > some tests are in order I believe. the implementation looks great, but let's make sure stuff are tested properly
> 
> @sagilaufer1992
> 
> It's already covered by some tests (acceptance and harness). Any specific use cases you had in mind?

@TomerHeber I'd like the memoization to be tested at least. to see it doesn't invoke the same call twice for the same parameters, does call for different parameters

**Comment by TomerHeber** [comment]
Got it. Makes sense.

**Comment by TomerHeber** [comment]
@sagilaufer1992 - added the unit tests for memoization.

**Review by sagilaufer1992 — APPROVED** [review]
LGTM, my comments were addressed
