### PR TITLE
Fix: env0_environment import missing some fields

### LINKED ISSUE #680: env0_environment import missing some fields
terraform cli command: 
`tf import env0_environment.this fc2dd64a-50bd-4a3b-82fd-bc838ffba0a1`

Terminal Output:
```
> env0/environment/test ➜ tf import env0_environment.this fc2dd64a-50bd-4a3b-82fd-bc838ffba0a1
data.env0_template.this: Reading...
data.env0_project.this: Reading...
data.env0_project.this: Read complete after 0s [id=7320dd7a-4822-426c-84b5-62ddd8be0799]
data.env0_template.this: Read complete after 1s [id=2af434dc-8ac4-4dd8-aa4d-2cdd396ab5c5]
env0_environment.this: Importing from ID "fc2dd64a-50bd-4a3b-82fd-bc838ffba0a1"...
env0_environment.this: Import prepared!
  Prepared env0_environment for import
env0_environment.this: Refreshing state... [id=fc2dd64a-50bd-4a3b-82fd-bc838ffba0a1]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

main.tf
```
data "env0_project" "this" {
  name                = "Core Payments - NonProd - 244172364962"
  parent_project_name = "Core Payments - Top Level"
}

data "env0_template" "this" {
  name = "FrontEnd Servers (EC2)"
}

resource "env0_environment" "this" {
  project_id                 = data.env0_project.this.id
  template_id                = data.env0_template.this.id
  approve_plan_automatically = true
  is_remote_backend          = true
  force_destroy              = true
}

terraform {
  required_providers {
    env0 = {
      source  = "env0/env0"
      version = ">= 1.4.11"
    }
  }
}

provider "env0" {
  organization_id = "bde19c6d-d0dc-4b11-a951-8f43fe49db92"
}
```

terraform.tfstate
```
{
  "version": 4,
  "terraform_version": "1.5.0",
  "serial": 1,
  "lineage": "4eb920f2-22f2-abe6-fccb-413c7ece53d6",
  "outputs": {},
  "resources": [
    {
      "mode": "data",
      "type": "env0_project",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/env0/env0\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "created_by": "google-oauth2|110563071352660869820",
            "description": "Dev Team",
            "id": "7320dd7a-4822-426c-84b5-62ddd8be0799",
            "name": "Core Payments - NonProd - 244172364962",
            "parent_project_id": "92c172d6-2122-4bca-8e16-9a0a5694e0bb",
            "parent_project_name": "Core Payments - Top Level",
            "role": ""
          },
          "sensitive_attributes": []
        }
      ]
    },
    {
      "mode": "data",
      "type": "env0_template",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/env0/env0\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "bitbucket_client_key": null,
            "description": "FrontEnd Servers powered by EC2 Instances",
            "github_installation_id": 11551359,
            "id": "2af434dc-8ac4-4dd8-aa4d-2cdd396ab5c5",
            "is_bitbucket_server": false,
            "is_github_enterprise": false,
            "is_gitlab_enterprise": false,
            "name": "FrontEnd Servers (EC2)",
            "path": "simple-ec2-instance",
            "project_ids": [
              "06db5c9b-78ca-4fc9-8fa6-0b9b54237637",
              "5e5b3cce-0417-42b6-a8a5-eb938d2054db",
              "6de20c9c-e5a2-49a3-aee5-00c03204ec3a",
              "7320dd7a-4822-426c-84b5-62ddd8be0799",
              "ce92cccf-1b95-482c-9a69-59071905f622",
              "edba559d-ae7f-467d-a2f8-1b5a54709ead"
            ],
            "repository": "https://github.com/env0/acme-demo",
            "retries_on_deploy": 0,
            "retries_on_destroy": 0,
            "retry_on_deploy_only_when_matches_regex": "",
            "retry_on_destroy_only_when_matches_regex": "",
            "revision": "main",
            "ssh_keys": [
              {
                "id": "d3d5da57-74ef-47bd-a5bd-11916a3dd33e",
                "name": "test gh private key"
              }
            ],
            "terraform_version": "1.1.7",
            "terragrunt_version": null,
            "token_id": null,
            "type": "terraform"
          },
          "sensitive_attributes": []
        }
      ]
    },
    {
      "mode": "managed",
      "type": "env0_environment",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/env0/env0\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "approve_plan_automatically": false,
            "auto_deploy_by_custom_glob": "",
            "auto_deploy_on_path_changes_only": false,
            "configuration": [],
            "deploy_on_push": false,
            "deployment_id": "e6ea7c67-d0ed-4791-8bd8-46be6934fcc5",
            "drift_detection_cron": null,
            "force_destroy": null,
            "id": "fc2dd64a-50bd-4a3b-82fd-bc838ffba0a1",
            "is_inactive": null,
            "is_remote_backend": null,
            "name": "FrontEnd Servers (EC2)-demo0718",
            "output": "{}",
            "project_id": "7320dd7a-4822-426c-84b5-62ddd8be0799",
            "revision": "main",
            "run_plan_on_pull_requests": false,
            "sub_environment_configuration": [],
            "template_id": "2af434dc-8ac4-4dd8-aa4d-2cdd396ab5c5",
            "terragrunt_working_directory": "",
            "ttl": "",
            "vcs_commands_alias": "",
            "without_template_settings": [],
            "workspace": null
          },
          "sensitive_attributes": [],
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    }
  ],
  "check_results": null
}
```
image

## Expected Result:
not sure all the fields missing but most important one thus far are workspace and is_remote_backend.
workspace = dev-demo0718
is_inactive = true
is_remote_backend = true

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #680 

### Solution

Found multiple (old) bugs in environment resource.
There was no acceptance test for import. Once I added the acceptance test I noticed all the issues.

1. Fixed bugs.
2. Updated acceptance test.

### CODE REVIEW

File: client/environment.go [hunk 1]
```diff
@@ -103,7 +103,7 @@ type Environment struct {
 	Id                          string        `json:"id"`
 	Name                        string        `json:"name"`
 	ProjectId                   string        `json:"projectId"`
-	WorkspaceName               string        `json:"workspaceName,omitempty"`
+	WorkspaceName               string        `json:"workspaceName,omitempty" tfschema:"workspace"`
```
Comment (TomerHeber) [inline client/environment.go:106]: this fixes "workspace".

File: env0/resource_environment.go [hunk 2]
```diff
@@ -557,7 +557,9 @@ func resourceEnvironmentCreate(ctx context.Context, d *schema.ResourceData, meta
 
 	d.SetId(environment.Id)
 	d.Set("deployment_id", environment.LatestDeploymentLogId)
-	d.Set("auto_deploy_on_path_changes_only", environment.AutoDeployOnPathChangesOnly)
+	if environment.AutoDeployOnPathChangesOnly != nil {
```
Comment (TomerHeber) [inline env0/resource_environment.go:560]: This was incorrect. Only assign if not nil.

File: env0/resource_environment.go [hunk 3]
```diff
@@ -1113,6 +1115,21 @@ func resourceEnvironmentImport(ctx context.Context, d *schema.ResourceData, meta
 	d.Set("deployment_id", environment.LatestDeploymentLogId)
 	setEnvironmentSchema(d, environment, environmentConfigurationVariables)
 
+	if environment.IsRemoteBackend != nil {
```
Comment (TomerHeber) [inline env0/resource_environment.go:1118]: the following have tfschema disabled (for various/historical reasons).
setting them manually.

File: env0/resource_environment.go [hunk 4]
```diff
@@ -1113,6 +1115,21 @@ func resourceEnvironmentImport(ctx context.Context, d *schema.ResourceData, meta
...
+	if environment.AutoDeployOnPathChangesOnly != nil {
+		d.Set("auto_deploy_on_path_changes_only", *environment.AutoDeployOnPathChangesOnly)
+	}
+
+	d.Set("is_inactive", false) // default is false.
+	if environment.IsArchived != nil {
+		d.Set("is_inactive", *environment.IsArchived)
+	}
+
+	d.Set("force_destroy", false)
```
Comment (TomerHeber) [inline env0/resource_environment.go:1131]: force_destory is always false when importing.
It's a schema field only.

File: env0/resource_environment_test.go [hunk 5]
```diff
@@ -26,7 +28,7 @@ func TestUnitEnvironmentResource(t *testing.T) {
 	updatedDriftDetectionCron := "*/10 1 * * *"
 
 	environment := client.Environment{
-		Id:            "id0",
+		Id:            uuid.New().String(),
```
Comment (TomerHeber) [inline env0/resource_environment_test.go:31]: import needs a real uuid. Otherwise it assumes it's a name.

File: env0/resource_environment_test.go [hunk 6]
```diff
@@ -182,6 +184,42 @@ func TestUnitEnvironmentResource(t *testing.T) {
 			})
 		})
 
+		t.Run("Import By Id", func(t *testing.T) {
```
Comment (TomerHeber) [inline env0/resource_environment_test.go:187]: This test was missing. Once I added it, the issues described in the bug were revealed (+ additional fields).

File: env0/resource_environment_test.go [hunk 7]
```diff
@@ -182,6 +184,42 @@ func TestUnitEnvironmentResource(t *testing.T) {
...
+				Steps: []resource.TestStep{
+					{
+						Config: createEnvironmentResourceConfig(environment),
+					},
+					{
+						ResourceName:            resourceNameImport,
+						ImportState:             true,
+						ImportStateId:           environment.Id,
+						ImportStateVerify:       true,
+						ImportStateVerifyIgnore: []string{"force_destroy"},
```
Comment (TomerHeber) [inline env0/resource_environment_test.go:198]: ignoring force_destroy - unique use-case.

File: env0/resource_environment.go (hunk 4 above)
Comment (sagilaufer1992) [reply env0/resource_environment.go:1131]: why is that always false when importing?

File: env0/resource_environment_test.go (hunk 6 above)
Comment (sagilaufer1992) [reply env0/resource_environment_test.go:187]: probably a gap in my understanding, how exactly does this test imitates an import?

File: env0/resource_environment_test.go [hunk 8]
```diff
@@ -182,6 +184,42 @@ func TestUnitEnvironmentResource(t *testing.T) {
...
+					TerragruntWorkingDirectory: environment.TerragruntWorkingDirectory,
+					VcsCommandsAlias:           environment.VcsCommandsAlias,
+					DeployRequest: &client.DeployRequest{
+						BlueprintId: templateId,
+					},
+					IsRemoteBackend: &isRemoteBackendFalse,
+				}).Times(1).Return(environment, nil)
+				mock.EXPECT().Environment(environment.Id).Times(3).Return(environment, nil)
+				mock.EXPECT().EnvironmentDestroy(environment.Id).Times(1)
+				mock.EXPECT().ConfigurationVariablesByScope(client.ScopeEnvironment, environment.Id).Times(3).Return(client.ConfigurationChanges{}, nil)
```
Comment (sagilaufer1992) [inline env0/resource_environment_test.go:219]: what is tested by these lines? the `times(3)` isn't really clear to me

**Review by sagilaufer1992 — APPROVED** [review]
looks good. I'd appreciate if you could answer my questions, even though they don't block the approval here

File: env0/resource_environment.go (hunk 4 above)
Comment (TomerHeber) [reply env0/resource_environment.go:1131]: Missing `default: false` in the schema.
Again... historical mistakes... in general it's a good practice to always set a default for type bool

File: env0/resource_environment_test.go (hunk 6 above)
Comment (TomerHeber) [reply env0/resource_environment_test.go:187]: no problem. Good question!
The following below are used for testing import.

`ImportState:             true,
						ImportStateId:           environment.Id,
						ImportStateVerify:       true,
`

File: env0/resource_environment_test.go (hunk 8 above)
Comment (TomerHeber) [reply env0/resource_environment_test.go:219]: Terraform calls "Read" multiple times.
First time after creation.
Another time to check for drifts.
Another time for import.
