### PR TITLE
Fix: project Data Source not outputting name/id properties

### LINKED ISSUE #229: Project Data Source not outputting name/id properties
To Recreate

```
resource "env0_project" "test_project" {
  name        = "Test-Project"
  description = "Test Description"
}

data "env0_project" "data_by_name" {
  name = env0_project.test_project.name
}

data "env0_project" "data_by_id" {
  id = env0_project.test_project.id
}

output "id_from_name" {
  value = data.env0_project.data_by_name.id
}

output "name_from_id" {
  value = data.env0_project.data_by_id.name
}
```

Both these `output`s will be empty, but they should hold the real values.

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #229 

### Solution
It looks like adding computed "true" fixes the issue. Not sure why.
Ideas?

### CODE REVIEW

File: env0/data_project.go [hunk 1]
```diff
@@ -19,12 +19,14 @@ func dataProject() *schema.Resource {
 				Description:  "the name of the project",
 				Optional:     true,
 				ExactlyOneOf: []string{"name", "id"},
+				Computed:     true,
```
Comment (TomerHeber) [inline env0/data_project.go:22]: Why would it fix the issue?
Strange...
output does work the second time running apply.

Comment (yaronya) [reply env0/data_project.go:22]: I'm not sure but I wouldn't hold any thought on this one. Let's ship this out ASAP.
The provider framework is FAR from being great 😞

**Review by yaronya — APPROVED** [review]
