### PR TITLE
Fix: do not fail on 'failed destroyed' environments when removing a project

### LINKED ISSUE #637: Do not fail on 'failed destroyed' environments when removing a project.
Internal discussion here:
https://env0.slack.com/archives/C01QBBEGBEH/p1681491655370129

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #637 

### Solution

Removed use-case and test.

### CODE REVIEW

File: env0/resource_project.go [hunk 1]
```diff
@@ -181,17 +174,16 @@ func resourceProjectDelete(ctx context.Context, d *schema.ResourceData, meta int
...
-					if err == nil {
-						done <- true
-						return
-					}
-
-					if aeerr, ok := err.(*ActiveEnvironmentError); ok {
-						if !aeerr.retry {
-							done <- true
-							return
+					if err != nil {
```
Comment (TomerHeber) [inline env0/resource_project.go:177]: tests were failing. This is now a more simplified version.
If error and error is retry, then retry.
In all other cases we're done (error or no error).

File: env0/resource_project.go [hunk 2]
```diff
@@ -139,13 +139,6 @@ func resourceProjectAssertCanDelete(ctx context.Context, d *schema.ResourceData,
 	}
 
 	for _, env := range envs {
-		if env.Status == "FAILED" && env.LatestDeploymentLog.Type == "destroy" {
```
Comment (TomerHeber) [inline env0/resource_project.go:142]: not needed, requested to be removed.

**Comment by igalklebanov** [comment]
[Add `remote state` section @ project policies form](https://trello.com/c/fWGXSi1B/9518-add-remote-state-section-project-policies-form)

**Review by yaronya — APPROVED** [review]
