### PR TITLE
Fix: template ssh keys read

### LINKED ISSUE #100: `resource "env0_template"` does not detect drifts in `ssh_keys`
1. Create `resource "env0_template"` without `ssh_keys` and apply it
2. Go to env0, attach an SSH key to the template, and save
3. run terraform plan, no changes are detected

### PR DESCRIPTION
**Pull request by yaronya**
### Issue & Steps to Reproduce / Feature Request
We aren't setting template ssh keys upon reading, so there's not drift detection for this attribute.
Fixes #100 

### Solution
Set `ssh_keys` attribute on read + convert `[]TemplateSshKey` `[]map[string]string` 

@RLRabinowitz this would probably affect your tests PR #105

### CODE REVIEW

File: env0/resource_template.go [hunk 1]
```diff
@@ -199,6 +199,13 @@ func resourceTemplateRead(ctx context.Context, d *schema.ResourceData, meta inte
 	d.Set("revision", template.Revision)
 	d.Set("type", template.Type)
 	d.Set("terraform_version", template.TerraformVersion)
+
+	var rawSshKeys []map[string]string
+	for _, sshKey := range template.SshKeys {
+		rawSshKeys = append(rawSshKeys, map[string]string{"id": sshKey.Id, "name": sshKey.Name})
```
Comment (eranelbaz) [inline env0/resource_template.go:205]: why we need this loop?
looks like `template.SshKeys` already contains what we need no?

**Review by eranelbaz — COMMENTED** [review]
small thing that looks off for me

File: env0/resource_template.go (hunk 1 above)
Comment (yaronya) [reply env0/resource_template.go:205]: That's the whole fix basically.
Terraform schema expects a "raw" type (as it's defined with `TypeMap` for this attribute) so we must convert it from a custom type such as `TemplateSshKey` to the expected `map[string]string`

Comment (eranelbaz) [reply env0/resource_template.go:205]: so can't we change it from "raw" map to out TempalteSshKey?

Comment (yaronya) [reply env0/resource_template.go:205]: Nope, schema doesn't support non raw types.

**Review by eranelbaz — APPROVED** [review]
I hate it, but 🤷

**Comment by RLRabinowitz** [comment]
> I hate it, but 🤷

That's Golang for you
