### PR TITLE
Fix: second apply of environment 'without_template_settings' causes r…

### LINKED ISSUE #507: Second apply of environment 'without_template_settings' causes recreation
This one seems like a bug, 
- create `resource env0_environment` with `without_template_settings`
- ~~change one of `without_template_settings` attributes such as `path`~~
- run `terraform apply` once again

it forces re-creation due to `template_id` changing back to `null` - instead of updating the environment

### PR DESCRIPTION
**Pull request by TomerHeber**
…ecreation

Resolves #507 

### Solution

Uses CustomizeDiff to avoid forceNew in templateless mode.

### CODE REVIEW

File: env0/resource_environment.go [hunk 1]
```diff
@@ -228,6 +228,15 @@ func resourceEnvironment() *schema.Resource {
...
 			},
 		},
+
+		CustomizeDiff: customdiff.ForceNewIf("template_id", func(ctx context.Context, d *schema.ResourceDiff, meta interface{}) bool {
+			// For templateless: any changes in template_id, no need to do anything (template id can't change).
+			// This is done due to historical bugs/issues.
+			if _, ok := d.GetOk("without_template_settings.0"); ok {
+				return false
+			}
+			return true
```
Comment (TomerHeber) [inline env0/resource_environment.go:238]: If the values don't change it ignores the "true" - this is exactly what we want.

**Review by avnerenv0 — APPROVED** [review]
QA'd and works perfectly 🤞 🍀
