### PR TITLE
Fix: drift issues with variable sets

### LINKED ISSUE #888: Using variable sets instead of regular variables causes drift detection
**Describe the bug**
When I have a template that creates an environment with a regular env var and then I change it to use variable sets, whenever I redeploy it assigns and unassigns the variable set. The first picture is one deploy and the second one is the next one (without changes to the tf code)

image

image

**To Reproduce**
Steps to reproduce the behavior.
If applicable, add a terraform snippet.

Had this first tf code:
```
terraform {
  required_providers {
    env0 = {
      source = "env0/env0"
    }
  }
}

provider "env0" {
  api_key    = *****
  api_secret = *****
  api_endpoint = *****
}

resource "env0_environment" "new_env" {
  name        = "new env"
  project_id  = *****
  template_id = *****

  configuration {
    name          = "TEST1234"
    type          = "terraform"
    value         = <<EOF
      {
        a = "world11111"
        b = {
          c = "d"
        }
      }
    EOF
    schema_format = "HCL"
  }
}
```

Then changed it to this and redeployed:
```
terraform {
  required_providers {
    env0 = {
      source = "env0/env0"
    }
  }
}

provider "env0" {
  api_key    = *****
  api_secret = *****
  api_endpoint = *****
}

resource "env0_environment" "new_env" {
  name        = "new env"
  project_id  = *****
  template_id = *****
}

resource "env0_variable_set" "organization_scope_example" {
  name        = "variable-set-example1"
  description = "description123"

  variable {
    name          = "TEST1234"
    type          = "terraform"
    value         = <<EOF
      {
        a = "world11111"
       b = {
         c = "d"
       }
     }
    EOF
    format = "hcl"
  }
}

resource "env0_variable_set_assignment" "assignment" {
  scope    = "environment"
  scope_id = env0_environment.new_env.id
  set_ids = [
    env0_variable_set.organization_scope_example.id,
  ]
}
```

**Expected behavior**
Have no changes in the plan when redeploying without changes

**Provider Version**
latest (1.19.1)

### LINKED ISSUE #894: bug - configuration variable that overrides a template variable in env0_environment shows drift
**Describe the bug**
A variable defined in the env0_template is being overwritten | specified in env0_environment that uses the template. 

the plan shows drift of parameters that are not meant to be re-configured (e.g. `regex`, `is_required`, `description`

```
  ~ resource "env0_environment" "default_projects" {
        id                               = "f29bfdca-1a77-49dd-b197-f2f0c4913a99"
        name                             = "Skunkworks Project"
      ~ variable_sets                    = [
          - "69cfcac0-5135-4967-a9d5-c6166f216f4c",
        ]
        # (13 unchanged attributes hidden)

      ~ configuration {
          - description  = "main project name for team" -> null
          ~ is_required  = true -> false
            name         = "team_name"
          - regex        = "[a-zA-Z0-9-_]*" -> null
            # (6 unchanged attributes hidden)
        }
    }
```

**To Reproduce**
1. Create an env0_template and env0_configuration_variable attached to template.
2. Create an env0_environment that is deployed from template with a `configuration` variable that overrides the template variable.

**Expected behavior**
the env0_environment should not show drift.

**Provider Version**
v1.19.1

**Screenshots**

**Additional context**
Sample code:

```
resource "env0_template" "projects" {
  name                   = "Team Projects"
  type                   = "opentofu"
  description            = "Project Factory for onboarding new teams"
  opentofu_version       = "latest"
  repository             = data.env0_template.this.repository
  path                   = "env0/projects"
  github_installation_id = data.env0_template.this.github_installation_id
}

resource "env0_template_project_assignment" "projects" {
  template_id = env0_template.projects.id
  project_id  = data.env0_environment.this.project_id
}

resource "env0_configuration_variable" "team_name" {
  template_id = env0_template.projects.id
  name        = "team_name"
  description = "main project name for team"
  is_required = true
  regex       = "[a-zA-Z0-9-_]*"
  type        = "terraform"
}

resource "env0_environment" "default_projects" {
  count = var.create_projects ? 1 : 0

  name                       = "${var.default_team_name} Project"
  project_id                 = data.env0_environment.this.project_id
  template_id                = env0_template.projects.id
  approve_plan_automatically = true
  is_remote_backend          = true
  removal_strategy           = "mark_as_archived"
  workspace                  = "${var.default_team_name}_project"

  configuration {
    name        = "team_name"
    value       = var.default_team_name
    type        = "terraform"
  }

  depends_on = [env0_configuration_variable.team_name]
}
```

### LINKED ISSUE #895: bug - variable set defined in env0_project, shows as something drifted to env0_environment
**Describe the bug**
A variable set defined in the project layer - is showing as a variable set that should be removed in env0_environment.  

**To Reproduce**
create a variable_set and assign it to the project.
create an env0_environment in the same project. 
run the deployment that uses env0_environment multiple times.

```
  # env0_environment.default_projects will be updated in-place
  ~ resource "env0_environment" "default_projects" {
        id                               = "f29bfdca-1a77-49dd-b197-f2f0c4913a99"
        name                             = "Skunkworks Project"
      ~ variable_sets                    = [
          - "69cfcac0-5135-4967-a9d5-c6166f216f4c",
        ]
        # (13 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Expected behavior**
No Drift Message.

**Provider Version**
1.19.1

**Screenshots**
n/a

**Additional context**
Sample Code:

```
resource "env0_api_key" "mgmt" {
  name = "control plane"
}

resource "env0_variable_set" "env0_keys" {
  name        = "Control-ENV0_API_KEY"
  description = "mgmt api key - control plane org api key"
  scope       = "project"
  scope_id    = data.env0_environment.this.project_id

  variable {
    name  = "ENV0_API_KEY"
    value = env0_api_key.mgmt.api_key_id
    type  = "environment"
  }

  variable {
    name         = "ENV0_API_SECRET"
    value        = env0_api_key.mgmt.api_key_secret
    type         = "environment"
    is_sensitive = true
  }
}

resource "env0_variable_set_assignment" "env0_keys" {
  scope    = "project"
  scope_id = var.project_id
  set_ids  = [env0_variable_set.env0_keys.id]
}

resource "env0_environment" "default_projects" {
  name                       = "${var.default_team_name} Project"
  project_id                 = var.project_id
  template_id                = env0_template.projects.id
  approve_plan_automatically = true
  is_remote_backend          = true
  removal_strategy           = "mark_as_archived"
  workspace                  = "${var.default_team_name}_project"

}
```

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #888 
fixes #894 
fixes #895 

### Solution

1. Fixed conflicts between environment sets and non-environment sets.
2. Filter out scopes assigned implicitly.
3. Updated tests.
4. Updated documentation to warn about conflicts.

### CODE REVIEW

File: client/configuration_set.go [hunk 1]
```diff
@@ -18,9 +18,10 @@ type UpdateConfigurationSetPayload struct {
 }
 
 type ConfigurationSet struct {
-	Id          string `json:"id"`
-	Name        string `json:"name"`
-	Description string `json:"description"`
+	Id              string `json:"id"`
+	Name            string `json:"name"`
+	Description     string `json:"description"`
+	AssignmentScope string `json:"assignmentScope"`
```
Comment (TomerHeber) [inline client/configuration_set.go:24]: added assignment scope to be able to filter implicit assignments.

File: env0/resource_environment.go [hunk 2]
```diff
@@ -433,7 +433,7 @@ func setEnvironmentSchema(ctx context.Context, d *schema.ResourceData, environme
 
 	setEnvironmentConfigurationSchema(ctx, d, configurationVariables)
 
-	if d.Get("variable_sets") != nil {
+	if variableSets, ok := d.GetOk("variable_sets"); variableSets != nil && ok {
```
Comment (TomerHeber) [inline env0/resource_environment.go:436]: same as "configuration" - if this field isn't used - ignore any use-cases related to it.
this will avoid possible conflicts with explicit assignment resource.

File: env0/resource_environment.go [hunk 3]
```diff
@@ -630,7 +630,9 @@ func getEnvironmentVariableSetIdsFromApi(d *schema.ResourceData, apiClient clien
 
 	var environmentVariableSetIds []string
 	for _, variableSet := range environmentVariableSets {
-		environmentVariableSetIds = append(environmentVariableSetIds, variableSet.Id)
+		if variableSet.AssignmentScope == "ENVIRONMENT" {
```
Comment (TomerHeber) [inline env0/resource_environment.go:633]: filter is required here... to avoid getting upper scopes variables (E.g. project or org).

File: env0/resource_variable_set_assignment.go [hunk 4]
```diff
@@ -181,6 +187,10 @@ func resourceVariableSetAssignmentRead(ctx context.Context, d *schema.ResourceDa
 	}
 
 	for _, apiConfigurationSet := range apiConfigurationSets {
+		if apiConfigurationSet.AssignmentScope != assignmentSchema.Scope {
+			continue
```
Comment (TomerHeber) [inline env0/resource_variable_set_assignment.go:191]: filter to avoid getting implicit variable sets...

File: env0/resource_variable_set_assignment.go [hunk 5]
```diff
@@ -87,6 +89,10 @@ func resourceVariableSetAssignmentUpdate(ctx context.Context, d *schema.Resource
 
 	// In API but not in Schema - delete.
 	for _, apiConfigurationSet := range apiConfigurationSets {
+		if apiConfigurationSet.AssignmentScope != assignmentSchema.Scope {
```
Comment (TomerHeber) [inline env0/resource_variable_set_assignment.go:92]: filter to avoid getting implicit variable sets... (from other scopes)

**Review by Yossi-kerner — COMMENTED** [review]
Regarding the general solution here, I think we can avoid code changes and just keep the docs like we do for regular variables. In the current solution, if a user uses the API or FE to assign variable sets we will ignore it and won’t show the drift

**Comment by TomerHeber** [comment]
> Regarding the general solution here, I think we can avoid code changes and just keep the docs like we do for regular variables. In the current solution, if a user uses the API or FE to assign variable sets we will ignore it and won’t show the drift

@Yossi-kerner - that's not going to be enough. Fixes are required here...

**Comment by Yossi-kerner** [comment]
> > Regarding the general solution here, I think we can avoid code changes and just keep the docs like we do for regular variables. In the current solution, if a user uses the API or FE to assign variable sets we will ignore it and won’t show the drift
> 
> @Yossi-kerner - that's not going to be enough. Fixes are required here...

But IIUC the fixes only hide the issue no? If there will be a drift detection we will miss that no?

**Comment by TomerHeber** [comment]
> > > Regarding the general solution here, I think we can avoid code changes and just keep the docs like we do for regular variables. In the current solution, if a user uses the API or FE to assign variable sets we will ignore it and won’t show the drift
> > 
> > 
> > @Yossi-kerner - that's not going to be enough. Fixes are required here...
> 
> But IIUC the fixes only hide the issue no? If there will be a drift detection we will miss that no?

@Yossi-kerner 

Not really...
One fix: The API will still return variable sets irrespective if they were set in the environment or not. This needs to be ignored if it was not set in the environment.
Second fix: The API to return variables returns both implicit and explicit assignments. Need to filter out implicit (inherited) assignments.

File: env0/resource_environment.go (hunk 2 above)
Comment (Yossi-kerner) [reply env0/resource_environment.go:436]: Sorry if it's a basic question but I'm pretty new to go and terraform provider so I would like to make sure 😅 Let's say we have an environment and we assign a variable set to it (by FE or API) will we see the drift there?

Comment (Yossi-kerner) [reply env0/resource_environment.go:436]: I see, I talked about it with @GiliFaroEnv0 and it looked weird that we won't show DD but if that's how we do it for configuration it might be the way 🤔 
I will raise it with the team and update you 😄

Comment (TomerHeber) [reply env0/resource_environment.go:436]: we are not hiding drifts...
you can either use the assignment resource or set the sets inline in the environment.
You cannot use both. Otherwise, you will have constant drifts/conflicts. (Same with configuration).

It just tests which one is used... if a resource assignments are used, it ignores anything inline in the environment.

Comment (GiliFaroEnv0) [reply env0/resource_environment.go:436]: maybe we just don't understand the code...
how are you checking if another resource is used?

Comment (TomerHeber) [reply env0/resource_environment.go:436]: It's simple (but not perfect):

if "variables-set" is set in the state, it means we use the "variables-set" inline use-case.
Otherwise, it's ignored.

**Review by Yossi-kerner — APPROVED** [review]
