### PR TITLE
Fix: template retry attributes

### LINKED ISSUE #83: Template Resource - Retry Regexes don't work
The retry regexes just do nothing

### LINKED ISSUE #84: Template Resource - removing retries_on_deploy/destroy doesn't disable retry
1. Apply a template with `retries_on_deploy`
2. Remove `retries_on_deploy`
3. Apply - the plan says `retries_on_deploy     = 4 -> null`
4. The retries don't actually change

### PR DESCRIPTION
**Pull request by yaronya**
Fixes #83 
Fixes #84

### CODE REVIEW

File: client/model.go [hunk 1]
```diff
@@ -76,12 +76,12 @@ const (
 
 type TemplateRetryOn struct {
 	Times      int    `json:"times,omitempty"`
-	ErrorRegex string `json:"errorRegex,omitempty"`
+	ErrorRegex string `json:"errorRegex"`
```
Comment (eranelbaz) [inline client/model.go:79]: why remove the `omitempty`?
if the user didn't put any what we want to do?

**Review by eranelbaz — APPROVED** [review]
it looks good,
just why we remove the omit empty?

File: client/model.go (hunk 1 above)
Comment (yaronya) [reply client/model.go:79]: We must remove `omitempty` to enable proper delete of this field
