### PR TITLE
Fix: inconsistent plan on the first apply when trying to create ssh_keys

### LINKED ISSUE #772: Inconsistent plan on the first apply when trying to create ssh_keys
**Describe the bug**
when trying to create `ssh_key` resource, the apply failed the first time for
```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for env0_template.null_template_3 to include new values learned so far during apply, provider "registry.terraform.io/env0/env0" produced an invalid new value for
│ .ssh_keys[0]: new element "id" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

On the second apply, the issue is resolved.

it is happened to one of the customers, and it fails their automation

**To Reproduce**
it is reproducible with the following template 
```
locals {

}

terraform {
  required_providers {
    env0 = {
      source = "env0/env0"
    }
  }
}

provider "env0" {
  api_key         = local.env0_api_key
  api_secret      = local.env0_api_secret
  api_endpoint    = local.api_endpoint
  organization_id = local.organization_id
}

resource "tls_private_key" "throwaway" {
  algorithm = "RSA"
}

output "public_key_you_need_to_add_to_github_ssh_keys" {
  value = tls_private_key.throwaway.public_key_openssh
}

resource "env0_ssh_key" "ssh_key" {
  count = 1
  name  = "sshkey"
  value = tls_private_key.throwaway.private_key_pem
}

data "env0_ssh_key" "data_ssh_key" {
  count = 1
  name  = "sshkey"

  depends_on = [env0_ssh_key.ssh_key]
}


```

**Expected behavior**
the ssh key is created successfully on the first apply.

**Provider Version**
1.16.3

**Screenshots**
image

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #772 

### Solution

Added computed to both fields to avoid race condition.

### CODE REVIEW

File: env0/data_sshkey.go [hunk 1]
```diff
@@ -18,12 +18,14 @@ func dataSshKey() *schema.Resource {
 				Type:         schema.TypeString,
 				Description:  "the name of the ssh key",
 				Optional:     true,
+				Computed:     true,
```
Comment (TomerHeber) [inline env0/data_sshkey.go:21]: Adding computed fixes some plan issues.

With computed:

```
      + path                  = "misc/null-resource"
      + repository            = "https://github.com/tomer-landesman/templates"
      + ssh_keys              = [
          + (known after apply),
        ]
      + terraform_version     = "0.15.1"
      + type                  = "terraform"
    }

Without computed it's missing the id in the first apply
```
   + repository            = "https://github.com/tomer-landesman/templates"
      + ssh_keys              = [
          + {
              + "name" = "sshkey"
            },
        ]
      + terraform_version     = "0.15.1"
```

Comment (TomerHeber) [reply env0/data_sshkey.go:21]: For context data is something like this (with name):

```
data "env0_ssh_key" "data_ssh_key" {
  count = 1
  name  = "sshkey"

  depends_on = [env0_ssh_key.ssh_key]
}
```

**Review by yaronya — APPROVED** [review]
