### PR TITLE
Fix: removing agent_project_assignment does not auto re-assign to the default agent

### LINKED ISSUE #914: removing `agent_project_assignment` does not auto re-assign to the default agent
**Describe the bug**
when using `agent_project_assignment` to assign a project to a specific agent, and then removing the `agent_project_assignment` resource, the project is not properly re-assigned to the default agent.

**To Reproduce**
* have org with at least 2 agents.
* use `agent_project_assignment` to assign project to 2nd agent (non-default)
* remove `agent_project_assignment`
* see project assignment - still stuck on 2nd agent.

**Expected behavior**
* after removing `agent_project_assignment` project should use default agent.

**Provider Version**
1.19.7

**Screenshots**
CleanShot 2024-07-30 at 09 16 59

**Additional context**

### PR DESCRIPTION
**Pull request by TomerHeber**
### Issue & Steps to Reproduce / Feature Request
fixes #914 

### Solution

The previous implementation was incorrect. The implementation was re-written.
1. Updated the API calls.
2. Updated the unit tests for the API calls.
3. Rewritten the resource implementation.
4. Rewritten the acceptance tests for the resource.
5. Updated the import example to use "project_id".

### CODE REVIEW

File: client/agent_project_assignment.go [hunk 1]
```diff
@@ -2,11 +2,11 @@ package client
 
 // Key is project id.
 // Value is agent id.
-type AssignProjectsAgentsAssignmentsPayload map[string]interface{}
+type AssignProjectsAgentsAssignmentsPayload map[string]string
 
 type ProjectsAgentsAssignments struct {
 	DefaultAgent   string                 `json:"defaultAgent"`
-	ProjectsAgents map[string]interface{} `json:"ProjectsAgents"`
+	ProjectsAgents map[string]interface{} `json:"projectsAgents"`
```
Comment (RLRabinowitz) [inline client/agent_project_assignment.go:9]: nit

Could be changed to `map[string]interface{}` as well, right?
```suggestion
	ProjectsAgents map[string]string `json:"projectsAgents"`
```

File: env0/resource_agent_project_assignment.go [hunk 2]
```diff
@@ -57,138 +43,99 @@ func resourceAgentProjectAssignment() *schema.Resource {
...
+	}
 
-	if _, err := apiClient.AssignAgentsToProjects(assignments.ProjectsAgents); err != nil {
-		return diag.Errorf("could not update project-agent assignments: %v", err)
+	if _, err := apiClient.AssignAgentsToProjects(payload); err != nil {
+		return diag.Errorf("failed to assign project '%s' to agent '%s': %v", assignment.ProjectId, assignment.AgentId, err)
 	}
 
-	d.SetId(newAssignment.GetId())
+	d.SetId(assignment.ProjectId)
```
Comment (RLRabinowitz) [inline env0/resource_agent_project_assignment.go:62]: Does it matter much if the ID is the project ID or assignment ID?

File: env0/resource_agent_project_assignment.go [hunk 3]
```diff
@@ -57,138 +43,99 @@ func resourceAgentProjectAssignment() *schema.Resource {
...
-	}
 
-	for projectId, agentId := range assignments.ProjectsAgents {
-		if projectId == newAssignment.ProjectId && agentId == newAssignment.AgentId {
-			return diag.Errorf("assignment for project id %v and agent id %v already exist", projectId, agentId)
-		}
+	var assignment AgentProjectAssignment
+	if err := readResourceData(&assignment, d); err != nil {
+		return diag.Errorf("schema resource data deserialization failed: %v", err)
 	}
```
Comment (RLRabinowitz) [inline env0/resource_agent_project_assignment.go:52]: We might still want this validation that was removed, but only making sure that there is no assignment, or that the assignment is to the default agent.

Removing this could mean that someone using a different Terraform/OpenTofu stack can attempt to manage the same resource there, and cause conflicts

File: env0/resource_agent_project_assignment.go [hunk 4]
```diff
@@ -57,138 +43,99 @@ func resourceAgentProjectAssignment() *schema.Resource {
...
-		return nil
+	for projectId, agent := range assignments.ProjectsAgents {
+		if projectId == assignment.ProjectId {
+			assignment.AgentId = agent.(string)
+			break
+		}
 	}
 
-	if err := writeResourceData(assignment, d); err != nil {
+	if err := writeResourceData(&assignment, d); err != nil {
```
Comment (RLRabinowitz) [inline env0/resource_agent_project_assignment.go:89]: Consider extracting this logic, which is shared with another action

File: env0/resource_agent_project_assignment_test.go [hunk 5]
```diff
@@ -11,219 +11,215 @@ import (
...
-						"agent_id":   agentId,
-					}),
-					Check: resource.ComposeAggregateTestCheckFunc(
-						resource.TestCheckResourceAttr(accessor, "id", agentId+"_"+projectId),
-						resource.TestCheckResourceAttr(accessor, "project_id", projectId),
-						resource.TestCheckResourceAttr(accessor, "agent_id", agentId),
-					),
-					PlanOnly:           true,
-					ExpectNonEmptyPlan: true,
+					Config: getConfig(&defaultAssignment),
```
Comment (RLRabinowitz) [inline env0/resource_agent_project_assignment_test.go:109]: I don't think that `ENV0_DEFAULT` is an actual agentId that is returned from API ever. I think it's just a value that is accepted when updating assignments, to indicate that this is the default agent

File: client/agent_project_assignment.go (hunk 1 above)
Comment (TomerHeber) [reply client/agent_project_assignment.go:9]: or "string" if it's always a string...

File: env0/resource_agent_project_assignment.go (hunk 2 above)
Comment (TomerHeber) [reply env0/resource_agent_project_assignment.go:62]: I don't think an assignment has an id.
So AFAIK it has to be the project_id (assuming one assignment per project).

File: env0/resource_agent_project_assignment_test.go (hunk 5 above)
Comment (TomerHeber) [reply env0/resource_agent_project_assignment_test.go:109]: Yeah I got that. that's what I did. Or am I misunderstanding?

File: env0/resource_agent_project_assignment.go (hunk 4 above)
Comment (TomerHeber) [reply env0/resource_agent_project_assignment.go:89]: need to be careful with over re-using code.
Golang (unlike NodeJS) is a strongly typed language, readability is more important.

Ill have another look, but if I decided not re-use code, it was probably for a good reason.

File: env0/resource_agent_project_assignment.go (hunk 3 above)
Comment (TomerHeber) [reply env0/resource_agent_project_assignment.go:52]: This is really what Terraform is for.. it will report a drift.
In any case, maintaining two states in Terraform is never good practice.

File: env0/resource_agent_project_assignment.go (hunk 4 above)
Comment (TomerHeber) [reply env0/resource_agent_project_assignment.go:89]: I could do a small reuse here... I'll push something in a couple of minutes.

Comment (TomerHeber) [reply env0/resource_agent_project_assignment.go]: Made the required changes. Thanks for pointing it out!

File: env0/resource_agent_project_assignment.go (hunk 3 above)
Comment (RLRabinowitz) [reply env0/resource_agent_project_assignment.go:77]: Oh OK. So this error wasn't really necessary before, IIUC

File: env0/resource_agent_project_assignment.go (hunk 2 above)
Comment (RLRabinowitz) [reply env0/resource_agent_project_assignment.go:87]: Up until now this was `GetId`, which is a combo of agentKey and project ID. And now it has changed. Wouldn't this affect existing configurations, causing drift or other issues?

File: client/agent_project_assignment.go (hunk 1 above)
Comment (RLRabinowitz) [reply client/agent_project_assignment.go:9]: Yeah, sorry, that's what I meant

File: env0/resource_agent_project_assignment_test.go (hunk 5 above)
Comment (RLRabinowitz) [reply env0/resource_agent_project_assignment_test.go:109]: Not sure why I commented that here 😅

File: env0/resource_agent_project_assignment.go (hunk 2 above)
Comment (RLRabinowitz) [reply env0/resource_agent_project_assignment.go:87]: I guess ProjectId makes more sense here as the ID. What would be the implications of this change on existing configurations?

Comment (TomerHeber) [reply env0/resource_agent_project_assignment.go:87]: yes you are correct.

The feature did not work as expected earlier, so fixing it now may cause a drift.
I think the best thing we can do is just add a note in the release notes about this breaking change. (That's what we've done in the past).

Comment (RLRabinowitz) [reply env0/resource_agent_project_assignment.go:87]: Alright. Could you please test the behaviour locally so we'd know exactly what users might see once they upgrade?

**Review by RLRabinowitz — APPROVED** [review]
As discussed, this is a breaking change for anyone with an existing state managing `agent_project_assignment`s. Anyone planning after upgrading to a new version containing this fix would get a drift, that would unassign and reassign the agent to the project.

The diff itself will look odd, sayin that the `agentKey` and `projectId` will be changed, and the "from" part of the change will be wrong.

We should make sure to mention that in the release notes, when detailing the breaking change
