### PR TITLE
Fix: harness test failures

### LINKED ISSUE #53: Integration tests fail - getConfigurationVariable - interface conversion
```
Stack trace from the terraform-provider-env0 plugin:

panic: interface conversion: interface {} is string, not *client.ApiClient

goroutine 30 [running]:
github.com/env0/terraform-provider-env0/env0.getConfigurationVariable(0x18b2c8d, 0x6, 0x0, 0x0, 0x0, 0x0, 0xc000120b80, 0x12, 0x0, 0x0, ...)
	/Users/avnersorek/env0/terraform-provider-env0/env0/data_configuration_variable.go:147 +0x8f3
github.com/env0/terraform-provider-env0/env0.dataConfigurationVariableRead(0x19ae020, 0xc000300240, 0xc000338600, 0x1882cc0, 0xc000683d80, 0xc0006b4760, 0xc00048f950, 0x100ff98)
	/Users/avnersorek/env0/terraform-provider-env0/env0/data_configuration_variable.go:103 +0x2af
```

### PR DESCRIPTION
**Pull request by yaronya**
### Issue & Steps to Reproduce / Feature Request
Fixes #53 

### Solution
1. Fixed wrong parameter passed to `getConfigurationVariable`, `getSshKeyById`, `getSshKeyByName`.
2. Fixed wrong logic of `getTemplateByName` and `getSshKeyByName`.

### CODE REVIEW

File: env0/data_sshkey.go [hunk 1]
```diff
@@ -60,22 +60,25 @@ func getSshKeyByName(name interface{}, meta interface{}) (client.SshKey, diag.Di
...
 	sshKeys, err := apiClient.SshKeys()
-	var sshKey client.SshKey
 	if err != nil {
 		return client.SshKey{}, diag.Errorf("Could not query ssh keys: %v", err)
 	}
-	if len(sshKeys) > 1 {
-		return client.SshKey{}, diag.Errorf("Found multiple SSH Keys for name: %s. Use ID instead or make sure SSH Keys names are unique %v", name, sshKeys)
-	}
+
+	var sshKeysByName []client.SshKey
```
Comment (avnerenv0) [inline env0/data_sshkey.go:67]: @yaronya you are the Go master - is there a normal way we could DRY this code ? 
Something like `getOnlyOneByName` ? 
We do the same thing for projects, ssh keys, templates, maybe more things ...

**Review by avnerenv0 — APPROVED** [review]
Looks good but if we can make this code better that might be better

File: env0/data_sshkey.go (hunk 1 above)
Comment (yaronya) [reply env0/data_sshkey.go:67]: @avnerenv0 Wouldn't say master 😿 
I gave that an effort but found myself struggling with the idea of polymorphism in Go which exists only for `interface`s and not for `struct`s (in this case we need a "parent struct" with a `Name` member).

Since I really wanna finish the UTs today - I let that one go. Do you think it's worth an issue?

Comment (avnerenv0) [reply env0/data_sshkey.go:67]: <div><br/>via <a href="https://giphy.com/bfv/">Braxton Family Values </a> on <a href="https://giphy.com/gifs/bfv-sisters-braxton-family-values-we-tv-3o7TKNRz1oDplVigj6">GIPHY</a></div>
